inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'test/**/*' # We're using RSpec

# Project-specific customizations:
Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

# These are added here instead of in .rubocop_todo.yml so that they
# won't be automatically removed when the TODO file is regenerated.
#
# Offenses that `rubocop --auto-gen-config` misses for some reason:
Layout/FirstArrayElementIndentation:
  Exclude:
    - 'app/models/data_digger.rb'