inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'test/**/*' # We're using RSpec
    - 'vendor/bundle/**/*' # GitHub Actions installs gems here
    - 'tmp/**/*'
    - 'minio-data/**/*'
    - 'couchdb-data/**/*'

# Project-specific customizations:
Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/controllers/loci_controller_spec.rb'
    - 'spec/controllers/pails_controller_spec.rb'

RSpec/ContextWording:
  Exclude:
    - 'spec/controllers/areas_controller_spec.rb'
    - 'spec/controllers/pails_controller_spec.rb'
    - 'spec/controllers/squares_controller_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/loci_controller_spec.rb'
    - 'spec/controllers/pails_controller_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 8

# These are added here instead of in .rubocop_todo.yml so that they
# won't be automatically removed when the TODO file is regenerated.
#
# Offenses that `rubocop --auto-gen-config` misses for some reason:
Layout/FirstArrayElementIndentation:
  Exclude:
    - 'app/models/data_digger.rb'