---
:version: 12
:design:
  "_id": _design/authdb
  :views:
    :config:
      :map: "function(doc){if (doc.type == 'config') emit(doc, doc);}"
    :users:
      :map: "function(doc){if (doc.uid) emit([doc.provider, doc.uid], doc);}"
