default: &default
  protocol: 'http'
  host: db
  port: 5984
  username: admin
  password: password
  prefix:
    main: opendig
    users: opendig_users

development:
  <<: *default
  suffix: development

test:
  <<: *default
  suffix: test
